In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("Preplacementdata.csv")

In [3]:
dataset

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.0,58.80,270000.0,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.5,66.28,200000.0,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.0,57.80,250000.0,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4.0,56.00,52.00,52.00,66.0,59.43,0.0,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5.0,85.80,73.60,73.30,96.8,55.50,425000.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211.0,80.60,82.00,77.60,91.0,74.49,400000.0,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,212.0,58.00,60.00,72.00,74.0,53.62,275000.0,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,213.0,67.00,67.00,73.00,59.0,69.72,295000.0,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,214.0,74.00,66.00,58.00,70.0,60.23,204000.0,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,215.0,62.00,58.00,53.00,89.0,60.22,0.0,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [4]:
gender_counts = dataset['gender'].value_counts()

In [6]:
# Extract the number of males
num_males = gender_counts.get('M', 0) # Use .get() to handle cases where 'Male' might not exist

print(f"Number of males: {num_males}")

Number of males: 139

In [7]:
male=dataset[dataset['gender']=='M']

In [8]:
male

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.0,58.80,270000.0,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.5,66.28,200000.0,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.0,57.80,250000.0,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4.0,56.00,52.00,52.00,66.0,59.43,0.0,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5.0,85.80,73.60,73.30,96.8,55.50,425000.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,210.0,62.00,72.00,65.00,67.0,56.49,216000.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
210,211.0,80.60,82.00,77.60,91.0,74.49,400000.0,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,212.0,58.00,60.00,72.00,74.0,53.62,275000.0,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,213.0,67.00,67.00,73.00,59.0,69.72,295000.0,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
214,215.0,62.00,58.00,53.00,89.0,60.22,0.0,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [9]:
placed=male[male['status']=='Placed']

In [10]:
placed

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.00,58.80,270000.0,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.50,66.28,200000.0,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.00,57.80,250000.0,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
4,5.0,85.80,73.60,73.30,96.80,55.50,425000.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
7,8.0,82.00,64.00,66.00,67.00,62.14,252000.0,M,Central,Central,Science,Sci&Tech,Yes,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,208.0,83.33,78.00,61.00,88.56,71.55,300000.0,M,Central,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
209,210.0,62.00,72.00,65.00,67.00,56.49,216000.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
210,211.0,80.60,82.00,77.60,91.00,74.49,400000.0,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,212.0,58.00,60.00,72.00,74.00,53.62,275000.0,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,213.0,67.00,67.00,73.00,59.00,69.72,295000.0,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed

In [12]:
not_placed=male[male['status']=='Not Placed']

In [13]:
not_placed

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
3,4.0,56.00,52.00,52.00,66.00,59.43,0.0,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
5,6.0,55.00,49.80,67.25,55.00,51.58,0.0,M,Others,Others,Science,Sci&Tech,Yes,Mkt&Fin,Not Placed
9,10.0,58.00,70.00,61.00,54.00,52.21,0.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Not Placed
14,15.0,62.00,47.00,50.00,76.00,54.96,0.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&HR,Not Placed
29,30.0,62.00,67.00,58.00,77.00,51.29,0.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Not Placed
34,35.0,62.00,51.00,52.00,68.44,62.77,0.0,M,Others,Others,Science,Others,No,Mkt&HR,Not Placed
36,37.0,51.00,44.00,57.00,64.00,51.45,0.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Not Placed
42,43.0,49.00,39.00,65.00,63.00,51.21,0.0,M,Others,Central,Science,Others,No,Mkt&Fin,Not Placed
51,52.0,54.40,61.12,56.20,67.00,62.65,0.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&HR,Not Placed
63,64.0,61.00,70.00,64.00,68.50,59.50,0.0,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Not Placed
65,66.0,54.00,47.00,57.00,89.69,57.10,0.0,M,Others,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed
82,83.0,63.00,67.00,74.00,82.00,60.44,0.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Not Placed
87,88.0,59.60,51.00,60.00,75.00,59.08,0.0,M,Central,Central,Science,Others,No,Mkt&HR,Not Placed
91,92.0,52.00,57.00,50.80,67.00,62.79,0.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&HR,Not Placed
93,94.0,52.00,62.00,54.00,72.00,55.41,0.0,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&HR,Not Placed
99,100.0,54.00,82.00,63.00,50.00,59.47,0.0,M,Central,Others,Commerce,Sci&Tech,No,Mkt&Fin,Not Placed
105,106.0,59.00,64.00,58.00,85.00,55.30,0.0,M,Central,Others,Science,Sci&Tech,No,Mkt&HR,Not Placed
106,107.0,61.08,50.00,54.00,71.00,65.69,0.0,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Not Placed
109,110.0,52.00,63.00,65.00,86.00,56.09,0.0,M,Central,Others,Science,Sci&Tech,Yes,Mkt&HR,Not Placed
111,112.0,51.00,54.00,61.00,60.00,60.64,0.0,M,Others,Others,Science,Sci&Tech,No,Mkt&HR,Not Placed
120,121.0,58.00,40.00,59.00,73.00,58.81,0.0,M,Others,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed
130,131.0,62.00,65.00,60.00,84.00,64.15,0.0,M,Central,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Not Placed
141,142.0,66.00,64.00,60.00,60.00,61.90,0.0,M,Central,Central,Science,Comm&Mgmt,No,Mkt&HR,Not Placed
144,145.0,52.00,50.00,61.00,60.00,58.52,0.0,M,Others,Others,Arts,Comm&Mgmt,No,Mkt&Fin,Not Placed
149,150.0,44.00,58.00,55.00,64.25,58.54,0.0,M,Central,Central,Arts,Comm&Mgmt,Yes,Mkt&HR,Not Placed
155,156.0,51.57,74.66,59.90,56.15,65.99,0.0,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&HR,Not Placed
158,159.0,67.00,63.00,64.00,60.00,61.87,0.0,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Not Placed
159,160.0,52.00,49.00,58.00,62.00,60.59,0.0,M,Central,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Not Placed
161,162.0,55.60,51.00,57.50,57.63,62.72,0.0,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Not Placed
167,168.0,67.90,62.00,67.00,58.10,75.71,0.0,M,Others,Others,Science,Sci&Tech,Yes,Mkt&Fin,Not Placed
169,170.0,59.96,42.16,61.26,54.48,65.48,0.0,M,Others,Others,Science,Sci&Tech,No,Mkt&HR,Not Placed
175,176.0,63.00,62.00,65.00,87.50,60.69,0.0,M,Others,Others,Science,Sci&Tech,No,Mkt&HR,Not Placed
181,182.0,62.00,60.33,64.21,63.00,60.02,0.0,M,Central,Others,Science,Sci&Tech,No,Mkt&HR,Not Placed
182,183.0,52.00,65.00,57.00,75.00,59.81,0.0,M,Others,Others,Arts,Others,Yes,Mkt&Fin,Not Placed
188,189.0,61.80,47.00,54.38,57.00,56.13,0.0,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Not Placed
194,195.0,52.00,55.00,56.30,59.00,64.74,0.0,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Not Placed
201,202.0,54.20,63.00,58.00,79.00,58.44,0.0,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed
206,207.0,41.00,42.00,60.00,97.00,53.39,0.0,M,Central,Central,Science,Comm&Mgmt,No,Mkt&Fin,Not Placed
214,215.0,62.00,58.00,53.00,89.00,60.22,0.0,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [15]:
female=dataset[dataset['gender']=='F']

In [16]:
female

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
6,7.0,46.00,49.2,79.0,74.28,53.29,0.0,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Not Placed
12,13.0,47.00,55.0,65.0,62.00,65.04,0.0,F,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed
13,14.0,77.00,87.0,59.0,68.00,68.63,218000.0,F,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
15,16.0,65.00,75.0,69.0,72.00,64.66,200000.0,F,Central,Central,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
17,18.0,55.00,67.0,64.0,60.00,67.28,0.0,F,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Not Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
197,198.0,83.96,53.0,91.0,59.32,69.71,260000.0,F,Others,Others,Science,Sci&Tech,No,Mkt&HR,Placed
198,199.0,67.00,70.0,65.0,88.00,71.96,0.0,F,Central,Central,Commerce,Others,No,Mkt&HR,Not Placed
204,205.0,74.00,73.0,73.0,80.00,67.69,210000.0,F,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
208,209.0,43.00,60.0,65.0,92.66,62.92,0.0,F,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed
213,214.0,74.00,66.0,58.0,70.00,60.23,204000.0,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed

In [17]:
placed=female[female['status']=='Placed']

In [18]:
placed

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
13,14.0,77.00,87.00,59.00,68.00,68.63,218000.0,F,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
15,16.0,65.00,75.00,69.00,72.00,64.66,200000.0,F,Central,Central,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
21,22.0,79.00,76.00,85.00,95.00,69.06,393000.0,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
22,23.0,69.80,60.80,72.23,55.53,68.81,360000.0,F,Others,Others,Science,Sci&Tech,No,Mkt&HR,Placed
23,24.0,77.40,60.00,64.74,92.00,63.62,300000.0,F,Others,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
30,31.0,64.00,73.50,73.00,52.00,56.70,250000.0,F,Central,Central,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
32,33.0,61.00,81.00,66.40,50.89,62.21,278000.0,F,Central,Central,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
33,34.0,87.00,65.00,81.00,88.00,72.78,260000.0,F,Others,Others,Science,Comm&Mgmt,Yes,Mkt&Fin,Placed
35,36.0,69.00,78.00,72.00,71.00,62.74,300000.0,F,Central,Central,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
37,38.0,79.00,76.00,65.60,58.00,55.47,320000.0,F,Central,Central,Science,Sci&Tech,No,Mkt&HR,Placed
38,39.0,73.00,58.00,66.00,53.70,56.86,240000.0,F,Others,Others,Science,Comm&Mgmt,No,Mkt&HR,Placed
40,41.0,78.00,77.00,80.00,60.00,66.72,287000.0,F,Central,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
44,45.0,77.00,73.00,81.00,89.00,69.70,200000.0,F,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
50,51.0,75.20,73.20,68.40,65.00,62.98,200000.0,F,Central,Central,Science,Comm&Mgmt,No,Mkt&HR,Placed
54,55.0,74.00,60.00,69.00,78.00,65.56,216000.0,F,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Placed
62,63.0,86.50,64.20,67.40,59.00,59.69,240000.0,F,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
76,77.0,66.50,70.40,71.93,61.00,64.27,230000.0,F,Others,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
80,81.0,69.00,62.00,69.00,67.00,62.35,240000.0,F,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&HR,Placed
85,86.0,83.84,89.83,77.20,78.74,76.18,400000.0,F,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
88,89.0,66.00,62.00,73.00,58.00,64.36,210000.0,F,Central,Central,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
89,90.0,84.00,75.00,69.00,62.00,62.36,210000.0,F,Others,Others,Science,Sci&Tech,Yes,Mkt&HR,Placed
90,91.0,85.00,90.00,82.00,92.00,68.03,300000.0,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
92,93.0,60.23,69.00,66.00,72.00,59.47,230000.0,F,Central,Central,Science,Comm&Mgmt,No,Mkt&Fin,Placed
96,97.0,76.00,70.00,76.00,66.00,64.44,300000.0,F,Central,Central,Science,Comm&Mgmt,Yes,Mkt&Fin,Placed
98,99.0,69.00,73.00,65.00,70.00,57.31,220000.0,F,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
102,103.0,77.00,61.00,68.00,57.50,61.31,300000.0,F,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
110,111.0,69.50,70.00,72.00,57.20,54.80,250000.0,F,Central,Central,Science,Sci&Tech,No,Mkt&HR,Placed
113,114.0,73.96,79.00,67.00,72.15,63.08,280000.0,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
115,116.0,73.00,63.00,66.00,89.00,60.50,216000.0,F,Others,Others,Science,Comm&Mgmt,No,Mkt&Fin,Placed
121,122.0,64.00,67.00,69.60,55.67,71.49,250000.0,F,Central,Others,Science,Sci&Tech,Yes,Mkt&HR,Placed
122,123.0,66.50,66.80,69.30,80.40,71.00,236000.0,F,Central,Central,Arts,Comm&Mgmt,Yes,Mkt&Fin,Placed
125,126.0,84.00,73.00,73.00,75.00,73.33,350000.0,F,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
126,127.0,79.00,61.00,75.50,70.00,68.20,210000.0,F,Others,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
127,128.0,72.00,60.00,69.00,55.50,58.40,250000.0,F,Others,Others,Science,Comm&Mgmt,No,Mkt&HR,Placed
131,132.0,74.90,57.00,62.00,80.00,60.78,360000.0,F,Others,Others,Science,Others,Yes,Mkt&Fin,Placed
134,135.0,77.44,92.00,72.00,94.00,67.13,250000.0,F,Central,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
135,136.0,72.00,56.00,69.00,55.60,65.63,200000.0,F,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Placed
138,139.0,82.00,64.00,73.00,96.00,71.77,250000.0,F,Others,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
148,149.0,77.00,86.00,56.00,57.00,64.08,240000.0,F,Central,Central,Arts,Others,No,Mkt&Fin,Placed
152,153.0,75.40,60.50,84.00,98.00,65.25,240000.0,F,Others,Central,Science,Sci&Tech,No,Mkt&Fin,Placed
164,165.0,67.16,72.50,63.35,53.04,65.52,250000.0,F,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
176,177.0,59.00,60.00,56.00,55.00,57.90,220000.0,F,Central,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
177,178.0,73.00,97.00,79.00,89.00,70.81,650000.0,F,Central,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
185,186.0,88.00,72.00,78.00,82.00,71.43,252000.0,F,Central,Central,Science,Others,No,Mkt&HR,Placed
193,194.0,60.00,63.00,56.00,80.00,56.63,300000.0,F,Central,Central,Arts,Others,Yes,Mkt&HR,Placed
197,198.0,83.96,53.00,91.00,59.32,69.71,260000.0,F,Others,Others,Science,Sci&Tech,No,Mkt&HR,Placed
204,205.0,74.00,73.00,73.00,80.00,67.69,210000.0,F,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,214.0,74.00,66.00,58.00,70.00,60.23,204000.0,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed